apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-rotatingconfigs
rules:
- apiGroups:
  - stable.example.com
  resources:
  - rotatingconfigs
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - patch
