apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
  namespace: shell-operator
spec:
  containers:
  - name: shell-operator
    image: localhost/shell-operator:latest
    imagePullPolicy: Never
  serviceAccountName: shell-operator
